install cypress/allure dependencies
HubSpotWebTeam/wt-eslint-browser pull request #13
Opened 2023-07-14 17:48 UTC by TyStelmach

### Summary of Changes 📋
We moved the defaults into this library in order to make setting up allure visualizations easier. We're running into some missing dependency issues, so we're also going to include them with this library. 

Blog PR: https://git.hubteam.com/MarketingWebTeam/blog/pull/973
Bug Ticket: https://issues.hubspotcentral.com/browse/FDNDEVOPS-2858

2023-07-14 17:50 UTC, swatinigam commented
👍

2023-07-14 20:01 UTC, TyStelmach commented on cypress.config.js
> +async function setupNodeEvents(on, config) {
I tried to handle this all in a single object, but when imported, the function is not working as expected, so this must be standalone.

2023-07-14 22:09 UTC, darkmavis1980 approved these changes

2023-07-14 23:10 UTC, darkmavis1980 requested changes
Actually, the workflows are failing, have a look at the logs

2023-07-17 19:47 UTC, TyStelmach commented
> Actually, the workflows are failing, have a look at the logs

This should be passing now, let me know if you see anything else on your end. @darkmavis1980

2023-07-17 20:50 UTC, darkmavis1980 approved these changes

2023-07-18 14:10 UTC, cfrisoli approved these changes

2023-07-18 14:10 UTC, merged